name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
        with:
          asdf_branch: v0.15.0
      - run: pnpm install --frozen-lockfile
      - name: Build
        run: ./build.sh
      - name: E2E tests
        run: ./test.sh
        env:
          FORCE_COLOR: true
