name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: pnpm install --frozen-lockfile
      - name: Test build
        run: ./build.sh
      - name: Test e2e
        run: ./test.sh
