name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
        with:
          asdf_branch: v0.15.0
      - run: pnpm install --frozen-lockfile

      - name: Set package version from tag
        working-directory: packages/nestjs-endpoints
        run: |
          version="${GITHUB_REF#refs/tags/}"
          echo "Setting package version to: $version"
          npm version "$version" --no-git-tag-version

      - name: Build package
        run: ./build.sh

      - run: cp README.md ./packages/nestjs-endpoints/README.md

      # - name: Publish package to npm
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
